LANGUAGES = {
    'ru': {
        'cpu_tray': "ЦПУ в трее",
        'ram_tray': "ОЗУ в трее",
        'cpu_info': "ЦПУ",
        'ram_loading': "ОЗУ",
        'swap_loading': "Подкачка",
        'disk_loading': "Диск",
        'lan_speed': "Сеть",
        'uptime_label': "Время работы",
        'settings_label': "Настройки",
        'exit_app': "Выход",
        'apply_label': "Применить",
        'cancel_label': "Отмена",
        'download_log': " Скачать ",
        'language': "Язык",
        'language_name': "Русский",
        'enable_logging': "Запись логирования",
        'keyboard_clicks': "Нажатия клавиш",
        'mouse_clicks': "Клики мыши",
        'power_off': "Выключение",
        'reboot': "Перезагрузка",
        'lock': "Блокировка",
        'settings': "Таймер",
        'minutes': "Минуты:",
        'action': "",
        'apply': "Применить",
        'cancel': "Отмена",
        'reset': "Сбросить",
        'confirm_title': "Подтверждение действия",
        'confirm_text_power_off': "Выключить компьютер?",
        'confirm_text_reboot': "Перезагрузить компьютер?",
        'confirm_text_lock': "Заблокировать экран?",
        'scheduled': "Запланировано",
        'error': "Ошибка",
        'error_minutes_positive': "Введите значение больше 0.",
        'notification': "Предупреждение",
        'action_in_1_min': "{} через 1 минуту.",
        'action_in_time': "{} через {} минут.",
        'cancelled': "Отменено",
        'cancelled_text': "Запланированное действие сброшено.",

        'token_bot': "Токен:",
        'id_chat': "ID чат:",
        'time_send': "Время уведомления (сек.):",
        'check_telegram': "Проверить",
        'bot_message': "Пожалуйста, введите токен бота и ID чата",
        'test_message': "Тестовое уведомление",
        'test_message_ok': "Тестовое сообщение успешно отправлено.",
        'test_message_error': "Не удалось отправить тестовое сообщение. Проверьте ваши данные.",
        'setting_telegram_error': "Не удалось сохранить конфигурацию Telegram.",
        'telegram_notification': "Уведомления в Telegram",
        'ok': "Успех",

        'discord_notification': 'Уведомления в Discord',
        'webhook_url': 'Webhook URL',
        'check_discord': 'Проверить',
        'webhook_required': 'Введите URL webhook Discord.',
        'setting_discord_error': 'Ошибка сохранения настроек Discord.',
    },
    'en': {
        'cpu_tray': "CPU in tray",
        'ram_tray': "RAM in tray",
        'cpu_info': "CPU",
        'ram_loading': "RAM",
        'swap_loading': "Swap",
        'disk_loading': "Disk",
        'lan_speed': "Network",
        'uptime_label': "Uptime",
        'settings_label': "Settings",
        'exit_app': "Exit",
        'apply_label': "Apply",
        'cancel_label': "Cancel",
        'download_log': "Download",
        'language': "Language",
        'language_name': "English",
        'enable_logging': "Enable logging",
        'keyboard_clicks': "Keyboard clicks",
        'mouse_clicks': "Mouse clicks",
        'power_off': "Power Off",
        'reboot': "Reboot",
        'lock': "Lock",
        'settings': "Settings",
        'minutes': "Minutes:",
        'action': "",
        'apply': "Apply",
        'cancel': "Cancel",
        'reset': "Reset",
        'confirm_title': "Confirm Action",
        'confirm_text_power_off': "Power off the computer?",
        'confirm_text_reboot': "Reboot the computer?",
        'confirm_text_lock': "Lock the screen?",
        'scheduled': "Scheduled",
        'error': "Error",
        'error_minutes_positive': "Please enter a value greater than 0.",
        'notification': "Notification",
        'action_in_1_min': "{} in 1 minute.",
        'action_in_time': "{} in {} minutes.",
        'cancelled': "Cancelled",
        'cancelled_text': "Scheduled action cancelled.",

        'token_bot': "Token:",
        'id_chat': "ID:",
        'time_send': "Interval (sek.):",
        'check_telegram': "Check",
        'bot_message': "Please enter the bot token and chat ID",
        'test_message': "Test notification",
        'test_message_ok': "Test message was sent successfully.",
        'test_message_error': "Failed to send test message. Please check your data.",
        'setting_telegram_error': "Failed to save Telegram configuration.",
        'telegram_notification': "Telegram notifications",
        'ok': "Success",

        'discord_notification': 'Discord Notifications',
        'webhook_url': 'Webhook URL',
        'check_discord': 'Test',
        'webhook_required': 'Please enter Discord webhook URL.',
        'setting_discord_error': 'Failed to save Discord settings.',
    },
    'cn': {
        'cpu_tray': "CPU在托盘",
        'ram_tray': "内存托盘显示",
        'cpu_info': "处理器",
        'ram_loading': "内存",
        'swap_loading': "交换分区",
        'disk_loading': "磁盘",
        'lan_speed': "网络",
        'uptime_label': "运行时间",
        'settings_label': "设置",
        'exit_app': "退出",
        'apply_label': "    应用    ",
        'cancel_label': "取消",
        'download_log': "下载日志",
        'language': "语言",
        'language_name': "中文",
        'enable_logging': "启用日志记录",
        'keyboard_clicks': "键盘点击",
        'mouse_clicks': "鼠标点击",
        'power_off': "关闭电源",
        'reboot': "重启",
        'lock': "锁屏",
        'settings': "设置",
        'minutes': "分钟:",
        'action': "",
        'apply': "应用",
        'cancel': "取消",
        'reset': "重置",
        'confirm_title': "确认操作",
        'confirm_text_power_off': "关闭计算机？",
        'confirm_text_reboot': "重启计算机？",
        'confirm_text_lock': "锁定屏幕？",
        'scheduled': "已安排",
        'error': "错误",
        'error_minutes_positive': "请输入大于0的值。",
        'notification': "通知",
        'action_in_1_min': "{} 还有1分钟。",
        'action_in_time': "{} 还有{}分钟。",
        'cancelled': "已取消",
        'cancelled_text': "已取消计划操作。",

        'token_bot': "机器人令牌:",
        'id_chat': "聊天ID:",
        'time_send': "发送时间（分钟",
        'check_telegram': "检查",
        'bot_message': "请输入机器人令牌和聊天ID",
        'test_message': "测试通知",
        'test_message_ok': "测试消息已成功发送。",
        'test_message_error': "无法发送测试消息。请检查您的信息。",
        'setting_telegram_error': "无法保存Telegram配置。",
        'telegram_notification': "Telegram 通知",
        'ok': "成功",
    },
    'de': {
        'cpu_tray': "CPU im Tray",
        'ram_tray': "RAM im Tray",
        'cpu_info': "CPU",
        'ram_loading': "RAM",
        'swap_loading': "Auslagerung",
        'disk_loading': "Festplatte",
        'lan_speed': "Netzwerk",
        'uptime_label': "Betriebszeit",
        'settings_label': "Einstellungen",
        'exit_app': "Beenden",
        'apply_label': "Übernehmen",
        'cancel_label': "Abbrechen",
        'download_log': "Herunterladen",
        'language': "Sprache",
        'language_name': "Deutsch",
        'enable_logging': "Protokolle",
        'keyboard_clicks': "Tastenklicks",
        'mouse_clicks': "Mausklicks",
        'power_off': "Herunterfahren",
        'reboot': "Neustart",
        'lock': "Sperren",
        'settings': "Einstellungen",
        'minutes': "Minuten:",
        'action': "",
        'apply': "Übernehmen",
        'cancel': "Abbrechen",
        'reset': "Zurücksetzen",
        'confirm_title': "Aktion bestätigen",
        'confirm_text_power_off': "Computer ausschalten?",
        'confirm_text_reboot': "Computer neu starten?",
        'confirm_text_lock': "Bildschirm sperren?",
        'scheduled': "Geplant",
        'error': "Fehler",
        'error_minutes_positive': "Bitte geben Sie einen Wert größer als 0 ein.",
        'notification': "Benachrichtigung",
        'action_in_1_min': "{} in 1 Minute.",
        'action_in_time': "{} in {} Minuten.",
        'cancelled': "Abgebrochen",
        'cancelled_text': "Geplante Aktion abgebrochen.",

        'token_bot': "Token:",
        'id_chat': "ID:",
        'time_send': "Intervall (sek.):",
        'check_telegram': "Prüfen",
        'bot_message': "Bitte geben Sie den Bot-Token und die Chat-ID ein",
        'test_message': "Testbenachrichtigung",
        'test_message_ok': "Testnachricht wurde erfolgreich gesendet.",
        'test_message_error': "Testnachricht konnte nicht gesendet werden. Bitte überprüfen Sie Ihre Angaben.",
        'setting_telegram_error': "Telegram-Konfiguration konnte nicht gespeichert werden.",
        'telegram_notification': "Telegram-Benachrichtigungen",
        'ok': "Erfolg",
    }
}
