LANGUAGES = {
    'ru': {
        'cpu_tray': "ЦПУ в трее",
        'ram_tray': "ОЗУ в трее",
        'cpu_info': " ЦПУ",
        'ram_loading': "ОЗУ",
        'swap_loading': "Подкачка",
        'disk_loading': "Диск",
        'lan_speed': "Сеть",
        'uptime_label': "Время работы",
        'settings_label': "Настройки",
        'exit_app': "Выход",
        'apply_label': "Применить",
        'cancel_label': "Отмена",
        'download_log': " Скачать ",
        'language': "Язык",
        'language_name': "Русский",
        'enable_logging': "Запись логирования",
        'keyboard_clicks': "Нажатия клавиш",
        'mouse_clicks': "Клики мыши",
        'power_off': "Выключение",
        'reboot': "Перезагрузка",
        'lock': "Блокировка",
        'settings': "Таймер",
        'minutes': "Минуты:",
        'action': "",
        'apply': "Применить",
        'cancel': "Отмена",
        'reset': "Сбросить",
        'confirm_title': "Подтверждение действия",
        'confirm_text_power_off': "Выключить компьютер?",
        'confirm_text_reboot': "Перезагрузить компьютер?",
        'confirm_text_lock': "Заблокировать экран?",
        'scheduled': "Запланировано",
        'error': "Ошибка",
        'error_minutes_positive': "Введите значение больше 0.",
        'notification': "Предупреждение",
        'action_in_1_min': "{} через 1 минуту.",
        'action_in_time': "{} через {} минут.",
        'cancelled': "Отменено",
        'cancelled_text': "Запланированное действие сброшено.",

        'token_bot': "Токен:",
        'id_chat': "ID чат:",
        'time_send': "Время уведомления (сек.):",
        'check_telegram': "Проверить",
        'bot_message': "Пожалуйста, введите токен бота и ID чата",
        'test_message': "Тестовое уведомление",
        'test_message_ok': "Тестовое сообщение успешно отправлено.",
        'test_message_error': "Не удалось отправить тестовое сообщение. Проверьте ваши данные.",
        'setting_telegram_error': "Не удалось сохранить конфигурацию Telegram.",
        'telegram_notification': "Уведомления в Telegram",
        'ok': "Успех",

        'discord_notification': 'Уведомления в Discord',
        'webhook_url': 'Webhook URL',
        'check_discord': 'Проверить',
        'webhook_required': 'Введите URL webhook Discord.',
        'setting_discord_error': 'Ошибка сохранения настроек Discord.',

        'system_status': 'Статус системы',
        'cpu': 'ЦПУ',
        'ram': 'ОЗУ',
        'swap': 'Подкачка',
        'disk': 'Диск',
        'network': 'Сеть',
        'uptime': 'Время работы',
        'keyboard': 'Клавиши',
        'mouse': 'Мышь',
        'clicks': 'кликов',
        'presses': 'нажатий',
        'gb': 'ГБ',
        'mbps': 'МБ/с',
        'temperature': '°C',

        'max_log_size_mb': 'Максимальный размер лог файла (МБ)',

        'ping_network': 'Проверить ping',
        'ping_running': 'Выполняется проверка сети…',
        'ping_done': 'Проверка завершена для',
        'ping_error': 'Ошибка при выполнении ping',
    },
    'en': {
        'cpu_tray': "CPU in tray",
        'ram_tray': "RAM in tray",
        'cpu_info': " CPU",
        'ram_loading': "RAM",
        'swap_loading': "Swap",
        'disk_loading': "Disk",
        'lan_speed': "Network",
        'uptime_label': "Uptime",
        'settings_label': "Settings",
        'exit_app': "Exit",
        'apply_label': "Apply",
        'cancel_label': "Cancel",
        'download_log': "Download",
        'language': "Language",
        'language_name': "English",
        'enable_logging': "Enable logging",
        'keyboard_clicks': "Keyboard clicks",
        'mouse_clicks': "Mouse clicks",
        'power_off': "Power Off",
        'reboot': "Reboot",
        'lock': "Lock",
        'settings': "Settings",
        'minutes': "Minutes:",
        'action': "",
        'apply': "Apply",
        'cancel': "Cancel",
        'reset': "Reset",
        'confirm_title': "Confirm Action",
        'confirm_text_power_off': "Power off the computer?",
        'confirm_text_reboot': "Reboot the computer?",
        'confirm_text_lock': "Lock the screen?",
        'scheduled': "Scheduled",
        'error': "Error",
        'error_minutes_positive': "Please enter a value greater than 0.",
        'notification': "Notification",
        'action_in_1_min': "{} in 1 minute.",
        'action_in_time': "{} in {} minutes.",
        'cancelled': "Cancelled",
        'cancelled_text': "Scheduled action cancelled.",

        'token_bot': "Token:",
        'id_chat': "ID:",
        'time_send': "Interval (sek.):",
        'check_telegram': "Check",
        'bot_message': "Please enter the bot token and chat ID",
        'test_message': "Test notification",
        'test_message_ok': "Test message was sent successfully.",
        'test_message_error': "Failed to send test message. Please check your data.",
        'setting_telegram_error': "Failed to save Telegram configuration.",
        'telegram_notification': "Telegram notifications",
        'ok': "Success",

        'discord_notification': 'Discord Notifications',
        'webhook_url': 'Webhook URL',
        'check_discord': 'Test',
        'webhook_required': 'Please enter Discord webhook URL.',
        'setting_discord_error': 'Failed to save Discord settings.',

        'system_status': 'System Status',
        'cpu': 'CPU',
        'ram': 'RAM',
        'swap': 'Swap',
        'disk': 'Disk',
        'network': 'Network',
        'uptime': 'Uptime',
        'keyboard': 'Keyboard',
        'mouse': 'Mouse',
        'clicks': 'clicks',
        'presses': 'presses',
        'gb': 'GB',
        'mbps': 'MB/s',
        'temperature': '°C',

        'max_log_size_mb': 'Maximum log file size (MB)',

        'ping_network': 'Ping network',
        'ping_running': 'Running network check…',
        'ping_done': 'Ping finished for',
        'ping_error': 'Error running ping',
    },
    'cn': {
        'cpu_tray': "CPU在托盘",
        'ram_tray': "内存托盘显示",
        'cpu_info': " 处理器",
        'ram_loading': "内存",
        'swap_loading': "交换分区",
        'disk_loading': "磁盘",
        'lan_speed': "网络",
        'uptime_label': "运行时间",
        'settings_label': "设置",
        'exit_app': "退出",
        'apply_label': "    应用    ",
        'cancel_label': "取消",
        'download_log': "下载日志",
        'language': "语言",
        'language_name': "中文",
        'enable_logging': "启用日志记录",
        'keyboard_clicks': "键盘点击",
        'mouse_clicks': "鼠标点击",
        'power_off': "关闭电源",
        'reboot': "重启",
        'lock': "锁屏",
        'settings': "设置",
        'minutes': "分钟:",
        'action': "",
        'apply': "应用",
        'cancel': "取消",
        'reset': "重置",
        'confirm_title': "确认操作",
        'confirm_text_power_off': "关闭计算机？",
        'confirm_text_reboot': "重启计算机？",
        'confirm_text_lock': "锁定屏幕？",
        'scheduled': "已安排",
        'error': "错误",
        'error_minutes_positive': "请输入大于0的值。",
        'notification': "通知",
        'action_in_1_min': "{} 还有1分钟。",
        'action_in_time': "{} 还有{}分钟。",
        'cancelled': "已取消",
        'cancelled_text': "已取消计划操作。",

        'token_bot': "机器人令牌:",
        'id_chat': "聊天ID:",
        'time_send': "发送时间（分钟",
        'check_telegram': "检查",
        'bot_message': "请输入机器人令牌和聊天ID",
        'test_message': "测试通知",
        'test_message_ok': "测试消息已成功发送。",
        'test_message_error': "无法发送测试消息。请检查您的信息。",
        'setting_telegram_error': "无法保存Telegram配置。",
        'telegram_notification': "Telegram 通知",
        'ok': "成功",

        'discord_notification': 'Discord 通知',
        'webhook_url': 'Webhook URL',
        'check_discord': '检查',
        'webhook_required': '请输入 Discord 的 Webhook URL',
        'setting_discord_error': '保存 Discord 设置时出错',

        'system_status': '系统状态',
        'cpu': 'CPU',
        'ram': '内存',
        'swap': '交换空间',
        'disk': '磁盘',
        'network': '网络',
        'uptime': '运行时间',
        'keyboard': '键盘',
        'mouse': '鼠标',
        'clicks': '次点击',
        'presses': '次按键',
        'gb': 'GB',
        'mbps': 'MB/s',
        'temperature': '°C',

        'max_log_size_mb': '日志文件的最大大小 (MB)',

        'ping_network': '网络连通性测试（ping）',
        'ping_running': '正在进行网络测试…',
        'ping_done': '已完成测试：',
        'ping_error': '执行 ping 时出错',
    },
    'de': {
        'cpu_tray': "CPU im Tray",
        'ram_tray': "RAM im Tray",
        'cpu_info': " CPU",
        'ram_loading': "RAM",
        'swap_loading': "Auslagerung",
        'disk_loading': "Festplatte",
        'lan_speed': "Netzwerk",
        'uptime_label': "Betriebszeit",
        'settings_label': "Einstellungen",
        'exit_app': "Beenden",
        'apply_label': "Übernehmen",
        'cancel_label': "Abbrechen",
        'download_log': "Herunterladen",
        'language': "Sprache",
        'language_name': "Deutsch",
        'enable_logging': "Protokolle",
        'keyboard_clicks': "Tastenklicks",
        'mouse_clicks': "Mausklicks",
        'power_off': "Herunterfahren",
        'reboot': "Neustart",
        'lock': "Sperren",
        'settings': "Einstellungen",
        'minutes': "Minuten:",
        'action': "",
        'apply': "Übernehmen",
        'cancel': "Abbrechen",
        'reset': "Zurücksetzen",
        'confirm_title': "Aktion bestätigen",
        'confirm_text_power_off': "Computer ausschalten?",
        'confirm_text_reboot': "Computer neu starten?",
        'confirm_text_lock': "Bildschirm sperren?",
        'scheduled': "Geplant",
        'error': "Fehler",
        'error_minutes_positive': "Bitte geben Sie einen Wert größer als 0 ein.",
        'notification': "Benachrichtigung",
        'action_in_1_min': "{} in 1 Minute.",
        'action_in_time': "{} in {} Minuten.",
        'cancelled': "Abgebrochen",
        'cancelled_text': "Geplante Aktion abgebrochen.",

        'token_bot': "Token:",
        'id_chat': "ID:",
        'time_send': "Intervall (sek.):",
        'check_telegram': "Prüfen",
        'bot_message': "Bitte geben Sie den Bot-Token und die Chat-ID ein",
        'test_message': "Testbenachrichtigung",
        'test_message_ok': "Testnachricht wurde erfolgreich gesendet.",
        'test_message_error': "Testnachricht konnte nicht gesendet werden. Bitte überprüfen Sie Ihre Angaben.",
        'setting_telegram_error': "Telegram Konfiguration konnte nicht gespeichert werden.",
        'telegram_notification': "Telegram Benachrichtigungen",
        'ok': "Erfolg",

        'discord_notification': 'Discord Benachrichtigungen',
        'webhook_url': 'Webhook-URL',
        'check_discord': 'Überprüfen',
        'webhook_required': 'Bitte geben Sie die Discord Webhook-URL ein.',
        'setting_discord_error': 'Fehler beim Speichern der Discord-Einstellungen.',

        'system_status': 'Systemstatus',
        'cpu': 'CPU',
        'ram': 'RAM',
        'swap': 'Swap',
        'disk': 'Festplatte',
        'network': 'Netzwerk',
        'uptime': 'Laufzeit',
        'keyboard': 'Tastatur',
        'mouse': 'Maus',
        'clicks': 'Klicks',
        'presses': 'Tastendrücke',
        'gb': 'GB',
        'mbps': 'MB/s',
        'temperature': '°C',

        'max_log_size_mb': 'Maximale Protokolldateigröße (MB)',

        'ping_network': 'Netzwerk prüfen (Ping)',
        'show_ping': 'Ping-Schaltfläche im Tray anzeigen',
        'ping_running': 'Netzwerkprüfung läuft…',
        'ping_done': 'Prüfung abgeschlossen für',
        'ping_error': 'Fehler beim Ausführen von Ping',
    },
    'it': {
        'cpu_tray': "CPU in tray",
        'ram_tray': "RAM in tray",
        'cpu_info': " CPU",
        'ram_loading': "RAM",
        'swap_loading': "Swap",
        'disk_loading': "Disco",
        'lan_speed': "Rete",
        'uptime_label': "Tempo di attività",
        'settings_label': "Impostazioni",
        'exit_app': "Esci",
        'apply_label': "Applica",
        'cancel_label': "Annulla",
        'download_log': " Scarica ",
        'language': "Lingua",
        'language_name': "Italiano",
        'enable_logging': "Registrazione log",
        'keyboard_clicks': "Tasti premuti",
        'mouse_clicks': "Clic del mouse",
        'power_off': "Spegnimento",
        'reboot': "Riavvio",
        'lock': "Blocco schermo",
        'settings': "Timer",
        'minutes': "Minuti:",
        'action': "",
        'apply': "Applica",
        'cancel': "Annulla",
        'reset': "Resetta",
        'confirm_title': "Conferma azione",
        'confirm_text_power_off': "Spegnere il computer?",
        'confirm_text_reboot': "Riavviare il computer?",
        'confirm_text_lock': "Bloccare lo schermo?",
        'scheduled': "Pianificato",
        'error': "Errore",
        'error_minutes_positive': "Inserisci un valore maggiore di 0.",
        'notification': "Avviso",
        'action_in_1_min': "{} tra 1 minuto.",
        'action_in_time': "{} tra {} minuti.",
        'cancelled': "Annullato",
        'cancelled_text': "Azione pianificata annullata.",

        'token_bot': "Token:",
        'id_chat': "ID chat:",
        'time_send': "Tempo notifica (sec.):",
        'check_telegram': "Controlla",
        'bot_message': "Inserisci il token del bot e l'ID della chat",
        'test_message': "Notifica di test",
        'test_message_ok': "Messaggio di test inviato con successo.",
        'test_message_error': "Impossibile inviare il messaggio di test. Verifica i dati.",
        'setting_telegram_error': "Impossibile salvare la configurazione Telegram.",
        'telegram_notification': "Notifiche Telegram",
        'ok': "Successo",

        'discord_notification': 'Notifiche Discord',
        'webhook_url': 'URL Webhook',
        'check_discord': 'Controlla',
        'webhook_required': 'Inserisci URL webhook Discord.',
        'setting_discord_error': 'Errore nel salvare le impostazioni Discord.',

        'system_status': 'Stato del sistema',
        'cpu': 'CPU',
        'ram': 'RAM',
        'swap': 'Swap',
        'disk': 'Disco',
        'network': 'Rete',
        'uptime': 'Tempo di attività',
        'keyboard': 'Tastiera',
        'mouse': 'Mouse',
        'clicks': 'clic',
        'presses': 'pressioni',
        'gb': 'GB',
        'mbps': 'MB/s',
        'temperature': '°C',

        'max_log_size_mb': 'Dimensione massima del file di log (MB)',

        'ping_network': 'Verifica rete (ping)',
        'ping_running': 'Verifica della rete in corso…',
        'ping_done': 'Verifica completata per',
        'ping_error': 'Errore durante l\'esecuzione di ping',
    },
    'es': {
        'cpu_tray': "CPU en bandeja",
        'ram_tray': "RAM en bandeja",
        'cpu_info': " CPU",
        'ram_loading': "RAM",
        'swap_loading': "Swap",
        'disk_loading': "Disco",
        'lan_speed': "Red",
        'uptime_label': "Tiempo de actividad",
        'settings_label': "Configuración",
        'exit_app': "Salir",
        'apply_label': "Aplicar",
        'cancel_label': "Cancelar",
        'download_log': " Descargar ",
        'language': "Idioma",
        'language_name': "Español",
        'enable_logging': "Registro de logs",
        'keyboard_clicks': "Pulsaciones de teclas",
        'mouse_clicks': "Clics del ratón",
        'power_off': "Apagar",
        'reboot': "Reiniciar",
        'lock': "Bloquear pantalla",
        'settings': "Temporizador",
        'minutes': "Minutos:",
        'action': "",
        'apply': "Aplicar",
        'cancel': "Cancelar",
        'reset': "Restablecer",
        'confirm_title': "Confirmar acción",
        'confirm_text_power_off': "¿Apagar el equipo?",
        'confirm_text_reboot': "¿Reiniciar el equipo?",
        'confirm_text_lock': "¿Bloquear la pantalla?",
        'scheduled': "Programado",
        'error': "Error",
        'error_minutes_positive': "Introduce un valor mayor que 0.",
        'notification': "Advertencia",
        'action_in_1_min': "{} en 1 minuto.",
        'action_in_time': "{} en {} minutos.",
        'cancelled': "Cancelado",
        'cancelled_text': "Acción programada cancelada.",

        'token_bot': "Token:",
        'id_chat': "ID de chat:",
        'time_send': "Tiempo notificación (seg.):",
        'check_telegram': "Comprobar",
        'bot_message': "Introduce el token del bot y el ID del chat",
        'test_message': "Notificación de prueba",
        'test_message_ok': "Mensaje de prueba enviado con éxito.",
        'test_message_error': "No se pudo enviar el mensaje de prueba. Verifica los datos.",
        'setting_telegram_error': "No se pudo guardar la configuración de Telegram.",
        'telegram_notification': "Notificaciones Telegram",
        'ok': "Éxito",

        'discord_notification': 'Notificaciones Discord',
        'webhook_url': 'URL Webhook',
        'check_discord': 'Comprobar',
        'webhook_required': 'Introduce la URL del webhook de Discord.',
        'setting_discord_error': 'Error al guardar la configuración de Discord.',

        'system_status': 'Estado del sistema',
        'cpu': 'CPU',
        'ram': 'RAM',
        'swap': 'Swap',
        'disk': 'Disco',
        'network': 'Red',
        'uptime': 'Tiempo de actividad',
        'keyboard': 'Teclado',
        'mouse': 'Ratón',
        'clicks': 'clics',
        'presses': 'pulsaciones',
        'gb': 'GB',
        'mbps': 'MB/s',
        'temperature': '°C',

        'max_log_size_mb': 'Tamaño máximo del archivo de registro (MB)',

        'ping_network': 'Probar red (ping)',
        'ping_running': 'Comprobando la red…',
        'ping_done': 'Comprobación finalizada para',
        'ping_error': 'Error al ejecutar ping',
    },
    'tr': {
        'cpu_tray': "Sistem çekmecesinde CPU",
        'ram_tray': "Sistem çekmecesinde RAM",
        'cpu_info': " CPU",
        'ram_loading': "RAM",
        'swap_loading': "Takas",
        'disk_loading': "Disk",
        'lan_speed': "Ağ",
        'uptime_label': "Çalışma süresi",
        'settings_label': "Ayarlar",
        'exit_app': "Çıkış",
        'apply_label': "Uygula",
        'cancel_label': "İptal",
        'download_log': " İndir ",
        'language': "Dil",
        'language_name': "Türkçe",
        'enable_logging': "Günlük kaydı",
        'keyboard_clicks': "Tuş vuruşları",
        'mouse_clicks': "Fare tıklamaları",
        'power_off': "Kapat",
        'reboot': "Yeniden başlat",
        'lock': "Ekranı kilitle",
        'settings': "Zamanlayıcı",
        'minutes': "Dakika:",
        'action': "",
        'apply': "Uygula",
        'cancel': "İptal",
        'reset': "Sıfırla",
        'confirm_title': "Eylemi onayla",
        'confirm_text_power_off': "Bilgisayar kapatılsın mı?",
        'confirm_text_reboot': "Bilgisayar yeniden başlatılsın mı?",
        'confirm_text_lock': "Ekran kilitlensin mı?",
        'scheduled': "Planlandı",
        'error': "Hata",
        'error_minutes_positive': "0'dan büyük bir değer girin.",
        'notification': "Uyarı",
        'action_in_1_min': "{} 1 dakika içinde.",
        'action_in_time': "{} {} dakika içinde.",
        'cancelled': "İptal edildi",
        'cancelled_text': "Planlanan eylem iptal edildi.",

        'token_bot': "Token:",
        'id_chat': "Sohbet ID:",
        'time_send': "Bildirim zamanı (sn.):",
        'check_telegram': "Kontrol et",
        'bot_message': "Bot token'ını ve sohbet ID'sini girin",
        'test_message': "Test bildirimi",
        'test_message_ok': "Test mesajı başarıyla gönderildi.",
        'test_message_error': "Test mesajı gönderilemedi. Verilerinizi kontrol edin.",
        'setting_telegram_error': "Telegram yapılandırması kaydedilemedi.",
        'telegram_notification': "Telegram Bildirimleri",
        'ok': "Başarılı",

        'discord_notification': 'Discord Bildirimleri',
        'webhook_url': 'Webhook URL',
        'check_discord': 'Kontrol et',
        'webhook_required': 'Discord webhook URL\'sini girin.',
        'setting_discord_error': 'Discord ayarları kaydedilirken hata.',

        'system_status': 'Sistem Durumu',
        'cpu': 'CPU',
        'ram': 'RAM',
        'swap': 'Swap',
        'disk': 'Disk',
        'network': 'Ağ',
        'uptime': 'Çalışma süresi',
        'keyboard': 'Klavye',
        'mouse': 'Fare',
        'clicks': 'tıklama',
        'presses': 'tuşlama',
        'gb': 'GB',
        'mbps': 'MB/s',
        'temperature': '°C',

        'max_log_size_mb': 'Maksimum günlük dosyası boyutu (MB)',

        'ping_network': 'Ağı kontrol et (ping)',
        'ping_running': 'Ağ kontrolü yapılıyor…',
        'ping_done': 'Kontrol tamamlandı:',
        'ping_error': 'Ping çalıştırılırken hata oluştu',
    },
    'fr': {
        'cpu_tray': "CPU dans la barre",
        'ram_tray': "RAM dans la barre",
        'cpu_info': " CPU",
        'ram_loading': "RAM",
        'swap_loading': "Swap",
        'disk_loading': "Disque",
        'lan_speed': "Réseau",
        'uptime_label': "Temps de fonctionnement",
        'settings_label': "Paramètres",
        'exit_app': "Quitter",
        'apply_label': "Appliquer",
        'cancel_label': "Annuler",
        'download_log': " Télécharger ",
        'language': "Langue",
        'language_name': "Français",
        'enable_logging': "Enregistrement des logs",
        'keyboard_clicks': "Frappes clavier",
        'mouse_clicks': "Clics souris",
        'power_off': "Arrêt",
        'reboot': "Redémarrage",
        'lock': "Verrouillage",
        'settings': "Minuterie",
        'minutes': "Minutes:",
        'action': "",
        'apply': "Appliquer",
        'cancel': "Annuler",
        'reset': "Réinitialiser",
        'confirm_title': "Confirmation d'action",
        'confirm_text_power_off': "Éteindre l'ordinateur?",
        'confirm_text_reboot': "Redémarrer l'ordinateur?",
        'confirm_text_lock': "Verrouiller l'écran?",
        'scheduled': "Planifié",
        'error': "Erreur",
        'error_minutes_positive': "Entrez une valeur supérieure à 0.",
        'notification': "Avertissement",
        'action_in_1_min': "{} dans 1 minute.",
        'action_in_time': "{} dans {} minutes.",
        'cancelled': "Annulé",
        'cancelled_text': "Action planifiée annulée.",

        'token_bot': "Token:",
        'id_chat': "ID chat:",
        'time_send': "Temps notification (sec.):",
        'check_telegram': "Vérifier",
        'bot_message': "Veuillez entrer le token du bot et l'ID du chat",
        'test_message': "Notification test",
        'test_message_ok': "Message test envoyé avec succès.",
        'test_message_error': "Impossible d'envoyer le message test. Vérifiez vos données.",
        'setting_telegram_error': "Impossible de sauvegarder la configuration Telegram.",
        'telegram_notification': "Notifications Telegram",
        'ok': "Succès",

        'discord_notification': 'Notifications Discord',
        'webhook_url': 'URL Webhook',
        'check_discord': 'Vérifier',
        'webhook_required': 'Entrez l\'URL webhook Discord.',
        'setting_discord_error': 'Erreur de sauvegarde des paramètres Discord.',

        'system_status': 'Sistem Durumu',
        'cpu': 'CPU',
        'ram': 'RAM',
        'swap': 'Swap',
        'disk': 'Disk',
        'network': 'Ağ',
        'uptime': 'Çalışma süresi',
        'keyboard': 'Klavye',
        'mouse': 'Fare',
        'clicks': 'tıklama',
        'presses': 'tuşlama',
        'gb': 'GB',
        'mbps': 'MB/s',
        'temperature': '°C',

        'max_log_size_mb': 'Taille maximale du fichier journal (Mo)',

        'ping_network': 'Vérifier le réseau (ping)',
        'ping_running': 'Vérification du réseau en cours…',
        'ping_done': 'Vérification terminée pour',
        'ping_error': 'Erreur lors de l\'exécution du ping',
    }
}
